### PR TITLE
Automatically get submodules with cmake

### PR DESCRIPTION
**Pull request by mirror3000**
Implement function to automatically get submodules when running cmake.
Also remove trailing whitespaces and replace some tabs lost among the spaces.

### CODE REVIEW

**Comment by markusobi** [comment]
I'm not sure if it is a good idea that running `cmake` updates all submodules.
Typically you are running cmake only once, when creating your build directory.
On consecutive build you typically just use `make` and cmake will only be automatically called by `make` if the `CmakeLists.txt` changed.

Problem 1:
I checkout some branch and I still need to update submodules manually (well I could call `cmake` to achieve this with this new change, but I think it is not the job of `cmake` to do this)

Problem 2:
`cmake` is also run by the clion IDE, when the IDE opens.

It all comes down to the point, that I don't expect `cmake` to change my current source directory/git when running cmake.

**Comment by mirror3000** [comment]
> Problem 1:
I checkout some branch and I still need to update submodules manually (well I could call cmake to achieve this with this new change, but I think it is not the job of cmake to do this)

Well, that's exactly why I made this patch, so you don't have to get them manually. They are just dependencies and not the scope of the project, so you should automatise this step.

> Problem 2:
cmake is also run by the clion IDE, when the IDE opens.

There is no discernible difference if you run git submodule. If they are already present, git will not download them again.

> It all comes down to the point, that I don't expect cmake to change my current source directory/git when running cmake. It's a huge side effect (but I agree that in most cases it does no harm).

There is a big difference between the source of the project and the source of the submodules:
- The source of the project is what you are working on and don't want it to be changed automatically
- The source of the submodules is code that just needs to be there in order for the build work.

This patch will not touch your code, it will just make sure that you got the submodules.

Because cmake and make are automation tools to help the building process, I think it's their job to get the submodules automatically.

**Comment by markusobi** [comment]
I sometimes change the code of the submodules, too (bgfx-cmake, Zenlib).
You are assuming, that the developer always wants the associated submodule commit.
That's not always the case.
With the proposed change, each invoke of `cmake` would check out the specified commits of the submodule.
For example:
I change Zenlib. Zenlib is in dirty state. What would `cmake` do now? Delete me changes? I don't know.
Next step: (ZenLib head is on commit `A`)
I commit my dirty changes (commit `B`) to the Zenlib submodule.
I run `cmake`. Cmake now secretly checks out the old Zenlib-commit `A`, that was specified by the current Regoth branch. Do you see what I mean?

**Comment by mirror3000** [comment]
Seems fair enough. I could to this as a git hook. Also I could add a hook for git commits, to check if the staged sources adhere to the coding convention.

**Comment by markusobi** [comment]
- Regarding the git hook for `submodule update`: feel free to do it
- Regarding the coding convention: That's a thing we already planned to add, but no one is currently working in it. See also #79 .
A while ago I started creating a [format file](https://github.com/markusobi/Clang-Format-Styles/blob/master/.clang-format), that more or less conforms with the current format used. (or at least what is mostly used in REGoth). I would be glad if you could use this as a base. If you want to change something feel free to do it (but comment it please). Or ask in the gitter chat which format is preferred.
There is also some [pre-commit](https://github.com/markusobi/Clang-Format-Styles/blob/master/pre-commit) laying around, but I'm not sure if it is useful (can't remember where I got it from).
- Regarding this pull request: Can you undo the `Get git submodules automatically with cmake` part, so I can merge the `Cleaned CMakeLists of trailing whitespaces and tabs` ?

**Comment by mirror3000** [comment]
Hey, I don't know how to edit pull requests with github. I'll make a different one just for the cleaned CMakeLists, if that's ok
Also I hope to finish the hooks this weekend and send you a different pull request with them.

**Comment by markusobi** [comment]
I haven't undone a commit yet too, but this should work:
`git revert <commit>`
in your case: `git revert eab6f8234d9b82716aae5e81d781ecfea437565f`
https://www.atlassian.com/git/tutorials/undoing-changes#git-revert
> Also I hope to finish the hooks this weekend and send you a different pull request with them.

ho hurry

**Pull request merged**
