### PR TITLE
"goto waypoint", "set time" and npc_clearinventory

### PR DESCRIPTION
**Pull request by Kaffeine**

### CODE REVIEW

**Comment by Aquaz** [comment]
I also think there should be something like "Print me valid waipoints" that would print the "major" waypoints that are valid in either game depending on which one you're running, such as WP_INTRO_SHORE for G1 etc.

**Comment by degenerated1123** [comment]
It should do an: "didn't find that one, here are some matching ones!"

Much like pressing tab twice in a terminal.

**Comment by Kaffeine** [comment]
I started to work on autocompletion by tab, but I have no time to work on it. Maybe this weekend.

@Aquaz Is there a way to distinguish a "major" waypoint from an ordinary one? Hardcode is not an option :)

**Comment by Aquaz** [comment]
https://www.worldofgothic.de/gothic/gothic_waypoint.htm

(you can translate to english if you're using google chrome)

**Comment by Kaffeine** [comment]
@Aquaz I already used that list to test the goto command. Still, there is no answer how to get the list by code.
Right now some (most) of the waypoints named differently, so maybe we do not import some "list of wp alias"? We also have all wp names in upper case.
Start point is "zCVobStartpoint:zCVob" and there is no point "start" or "START" (I'm using G1 files from steam).

**Comment by Aquaz** [comment]
We could store a mapping in a JSON configuration file designed specifically for console stuff, there already is code that manages loading of JSONs, so the actual waypoints could be aliased to some easy to read and type form. Appropriate configuration file would be fetched based on which world is loaded.

**Pull request merged**
