### PR TITLE
Add giveitem console command

### PR DESCRIPTION
**Pull request by rose27**
I have added a giveore command. It comes with Bloodwyn's approval.

### CODE REVIEW

**Comment by markusobi** [comment]
What happens when the amount is not a number? Application crash?
See [exceptions](http://en.cppreference.com/w/cpp/string/basic_string/stol)

**Comment by rose27** [comment]
Yes, I'm aware of that but my implementation is based on other commands.
I assumed that we take responsibility for passing correct arguments.

**Comment by degenerated1123** [comment]
That would happen on all of the console commands. Should put a try-block into the console-class

**Comment by markusobi** [comment]
Idea:
How about a generic `give`/`insert` command: `give <item> [<count>]` where `count` is optional and defaults to 1?
Item is placed on ground like the Gothic insert command or given to the inventory of the player (I like this one more).
It accepts displayname or datfilename (like goto npc / kill / knockout) and compares the strings to be somewhat equal (See https://github.com/REGoth-project/REGoth/blob/f1b3195f0844e551b55a975c3c6cd62ca57c600e/src/logic/ScriptEngine.cpp#L349)

**Comment by rose27** [comment]
I thought about something like this but I wanted to try something easier just to get familiar with console. Nevertheless I second this idea.

I will remove hardcoded value soon

**Comment by rose27** [comment]
Instead of giveore command I implemented giveitem command. It's simpler than what @markusobi suggested but it's something to start with.

@degenerated1123 It should now check if the item exists and if it is an item.

**Comment by degenerated1123** [comment]
Usage of `getItemFromSymbol` is not correct here. Thus. in the current implementation, I cannot insert many valid items (Only items that have been spawned before).

What `getItemFromSymbol` does is, it looks up the *last instance* that was *created* of the given instance-name. Behavior is much more useful on NPCs, where you only have one instance of them most of the time (Like, "Give me the instance of Lee!"), but I had to implement for items as well, since the npcs script-state needed it.

You can just drop the check and everything should be correct.

**Comment by markusobi** [comment]
The command in the current form is not really useful yet. I tried it and the only item I was able to insert (without looking up in the insert-codes-database) was ulumulu.
To make this command useful you really need some kind of fuzzy search. I've already implemented a basic function (used for kill/knockout/tp) `Utils::containsLike`, which you can use for that. https://github.com/rose27/REGoth/blob/master/src/utils/Utils.h#L458

Also inserting via displayname would be useful. Just implement something like `ScriptEngine::findWorldNPCsNameLike`, but for items instead of npcs. https://github.com/REGoth-project/REGoth/blob/master/src/logic/ScriptEngine.cpp#L343

So in the end one can simply type in:
`giveitem fackel` or `giveitem torch` and it just works.

**Comment by markusobi** [comment]
I realized that it is not trivial to find out the display names (`C_Item.description`) of items, _which had not been inserted before_. The fields of the C_Item instance get initialized by a [script function](https://github.com/degenerated1123/ZenLib/blob/af104a9f74a4b77f459be87068bccca613ec163f/daedalus/DaedalusGameState.cpp#L323). I was not aware of this. (For items already present in the running game, the `C_Item.description` field should work for retrieving the display name)

For now it should be enough to just use the script name. There is a minor issue with the current implementation, because it allows all `PARSymbols` to be inserted as items. This also includes things like `ZS_SLEEPER` or `ZS_SLEEPER_LOOP`. I am not sure if there is a way to check on `PARSymbol` if it is an item. Maybe there is no way at all to differentiate between items and npcs or other instances. Anybody got an insight in this?

If there is no way to check on a `PARSymbol` if it is an item, you are good to go and I'll merge it.

**Pull request merged**
