### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by versable**
This pull requests adds a make target that can be used for formatting every source file with:

`make clang-format`

Additionally I added a git pre-commit hook that runs clang-format on added/changed git files and a simple bash script that symlinks the hook to `.git/hooks/*`

Rational: #79

### CODE REVIEW

**Comment by markusobi** [comment]
this is a test pull request. don't merge it

**Comment by versable** [comment]
If there is nothing else to do, this PR is ready for a merge

**Comment by markusobi** [comment]
There are two things to do before we can merge this. We should merge all other branches before, because they would otherwise reintroduced unformatted code/merge conflicts all over the place.
What we could merge right now is the clang-format-file + git-hooks + make target. So we can format the whole code at a later point when all development has converged.

**Comment by versable** [comment]
Considering we only have 2 other PR, with minimal changes, I'd say better merge now then later. This project is only going to get more traction, so I am for a merge.

**Comment by markusobi** [comment]
#214 and #215 can be merged I guess. There is still one more branch [camera-animation](https://github.com/REGoth-project/REGoth/tree/camera-animation). @degenerated1123 are you still working on it?

**Pull request merged**
