### PR TITLE
Fixing Apple Linking Error openal

### PR DESCRIPTION
**Pull request by noahndertaler**

### CODE REVIEW

**Comment by frabert** [comment]
From my testing, it should be `OpenAL` even on Linux, so there should be no need to add a check for `APPLE`.

Not sure though

**Comment by noahndertaler** [comment]
Yes thought so too, but was confused because it worked in previous versions.

**Comment by frabert** [comment]
I think it all went awry since the OpenAL update

**Comment by frabert** [comment]
I think this can be closed now that #327 has been merged.

**Pull request closed without merging**
