### PR TITLE
Sky textures

### PR DESCRIPTION
**Pull request by degenerated1123**
Added rendering of the Sky-Dome in G2 and the Sky-Plane for G1.

### CODE REVIEW

**Comment by degenerated1123** [comment]
Should be working now.

**Comment by markusobi** [comment]
I fixed some compile errors related to the bgfx update.
Now the sky is completely greyscale (I see clouds, but no colors) in G1 & G2
Also the program crashes in `RenderSystem::destroyShaders()` when exiting the game.

Might be due to shaders not copied to right location?

**Comment by degenerated1123** [comment]
Seems like the shaders haven't been loaded. The default bgfx-shaders seem to turn everything red-ish/gray. 

This is probably caused by the shader-format being outdated since master moved to a new bgfx version. I'll have a look at it!

**Comment by degenerated1123** [comment]
I could reproduce the issue and fixed it by recompiling all shaders for the new bgfx version.

**Comment by Kukunin** [comment]
I re-run test, and it made PR green

**Comment by degenerated1123** [comment]
Then someone please merge it :)

**Pull request merged**
