### PR TITLE
If the g2 addon is available then prefer its textures and show its st…

### PR DESCRIPTION
**Pull request by kapitaenzufall**
…artscreen with its fonts.

Loads the addon vdfs of g2 before the default ones. Then if the addon is installed its textures will be prefered and the proper startscreen of the g2 addon is shown. This will only work with the pr I made at autalien/zenlib.

### CODE REVIEW

**Comment by CarnageMarkus** [comment]
vdfs loading order should be by timestamp,  hardcoding it to load files with "Addon" is rather very short sighted and not good solution

**Comment by tomedi** [comment]
@CarnageMarkus is right. See issue #192

**Comment by frabert** [comment]
The issue now is mainly to find a clean way to portably read a file's modification date

**Comment by kapitaenzufall** [comment]
As mentioned at #192 I would write a method at FileIndex which reads the timestamp from the vdfs file and return this somehow. The question is at which format the timestamp is returned. Any ideas?

**Comment by frabert** [comment]
You _cannot_ read the timestamp of the whole VDF archive, but you can read the timestamp of the individual files inside of the archive. The problem is: if there are multiple archives that load files with the same name, the last archive to be loaded wins, so we need to load the archives in order of increasing timestamp.

BTW, if you're intrested in checking the date of individual files, [PHYSFS_getLastModTime](https://icculus.org/physfs/docs/html/physfs_8h.html#a58e182a3deb67dd780f1de23440fa3e5) is what you're looking for, it returns the number of seconds since the Unix epoch. VDF files store timestamps as MS-DOS epochs, but the conversion should be handled by PhysFS already

**Comment by frabert** [comment]
> Had a different behaviour. The startscreen image of the g2 addon was only shown when I had loaded the addon vdfs before the g2 ones.
Yes it's possible I had it reversed, but it could be configurable based on what it is passed to PHYSFS_mount on [this](https://github.com/ataulien/ZenLib/blob/master/vdfs/fileIndex.cpp#L29) line

> Why can not I just parse this datetime and use it to load newer vdf archive files before older ones?
Because that would require ad-hoc parsing of the archives _before_ they are added to the index. Totally doable, but not with the present set of functionality

**Comment by kapitaenzufall** [comment]
> Because that would require ad-hoc parsing of the archives before they are added to the index. Totally doable, but not with the present set of functionality
I could write those functionality. Would this be an acceptable solution?

**Comment by frabert** [comment]
It would be acceptable to me, [here](https://github.com/REGoth-project/REGoth/wiki/VDF-File-Format) is some info I've written about VDF in case you need it

**Comment by kapitaenzufall** [comment]
>  here is some info I've written about VDF in case you need it

Even if I am not going to need it, it is at least interesting, thanks!

> It would be acceptable to me

Then I will give it a try.

**Comment by kapitaenzufall** [comment]
Those commits I updated will only with the pr https://github.com/ataulien/ZenLib/pull/26.

**Comment by kapitaenzufall** [comment]
If there are no further comments I think its ready to merge.

**Pull request merged**
