### PR TITLE
Log menu

### PR DESCRIPTION
**Pull request by kapitaenzufall**
This pr contains a simple version of the log menu which can be accessed through n or l. The log topics and entries are already scrollable but do not behave exactly like the original log menu. All log entries are saved inside a json file. I have only run it under windows, build it with msvc and tested it with Gothic I & II. I would be glad if someone could test it on a different OS. Cause I am new to git I am not sure if I threated the submodules the right way. Let me know if I should fix something. Hope you like it :)

### CODE REVIEW

**Comment by degenerated1123** [comment]
I tried it and it worked pretty well, good job!

To compile on my system (GCC, Linux), I had to do a minor modification though. the compiler complains that control flow can reach a path where no value is returned from the function here:
```cpp
MenuItem* UI::Menu_Log::findMenuItem(const std::string& instance)
{
    for (auto iterator = m_Items.begin(); iterator != m_Items.end(); iterator++)
        if (iterator->second->getItemScriptData().instanceSymbol == getItemScriptData(instance).instanceSymbol)
            return iterator->second;
}
```

I added a `return nullptr;` to the end and it compiled fine. However, everywhere that function is called, you should check for a return value of `nullptr` then of course, or else we'll get some nasty null-pointer accesses.

Also, small side note: I found some of these in your code:
```cpp
for (auto iterator = m_Items.begin(); iterator != m_Items.end(); iterator++) { iterator->second->... }
```
Since C++11 we can simply do:
```cpp
for(auto& item : m_Items) { item.second->... }
```

**Comment by degenerated1123** [comment]
Also I noticed that the log wouldn't survive a level-switch. But I think thats for another PR. Having a log menu at all is already nice!

**Comment by kapitaenzufall** [comment]
I made these changes you suggested me. Its been a while since I wrote some C++ code so I  appreciate every coding advice I can get :)

**Comment by markusobi** [comment]
The function `getDayFormatted` is not really necessary. All it does is to_string(int) + "."

**Comment by kapitaenzufall** [comment]
I thought it would be nice to encapsulate the fomatting but it unnecessary bloat up the code as well. I have removed it.

**Comment by degenerated1123** [comment]
@marcusobi Im not agreeing with removing such a method/function. IMHO a function should do as few different things as possible and have a name which is describing that exact behavior. This spares you the need to put a comment, which might get outdated, but the code rather documents itself. If someone were to change the format of the shows time, he instantly knew where to look.

I suggest reading "Clean Code" by Robert C. Martin, it contains some excellent suggestions and insights. I read it only a few months ago and liked it a lot :)

**Comment by markusobi** [comment]
The reasons why I tended to not add a function in this case:
- It's a functionality, that is used/needed only in one place. Other usages might need slightly different formats.
- I didn't see it as a format more like a: I need a "<day>." here
- small code bloat

Though I see, that it's more expressive to call `getDayFormatted`, so feel free to revert it, no hard feelings.

@kapitaenzufall 
To revert a commit (and keeping the history) you can use `git revert commithash`. It adds a new commit, which undoes the changes of the commit.

**Comment by kapitaenzufall** [comment]
@degenerated1123 
Interesting that you mention this book. I started reading it two weeks ago because a colleague heavily recommended it^^

@markusobi 
I have done the git revert, should be fine.

**Comment by degenerated1123** [comment]
By the way, I remember the log crashing on me when I tried it with Gothic 2. I went to lobarts farm and talked to some of the guys. When looking around in the log it crashed. Sorry that I can't give you any more insights into this, but it would be great if you took a look at it!

**Comment by kapitaenzufall** [comment]
I made lobarts quest and talked to all the people around, but unfortunately I was not able to reproduce this issue under windows with Gothic 2. What I encountered was a crash if I start a new game, then load a savegame, start a new game and so on... at some point it crashes at "postprocessing worldmesh". But this also occur at the latest release build "REGoth-FixKeyBindings-0.3.452.zip".

**Comment by degenerated1123** [comment]
Okay, then I'll see if I can reproduce it when I'm back home. 

The crash you encountered may be because of a memory leak still in there.

By the way, if @markusobi doesn't see any more problems, I think we can merge this. 
It's a really great addition into making the game more complete. Good work!

**Comment by markusobi** [comment]
The game crash after starting new game several times is a known problem and also affects master branch. The bigger the map, the less new games you need until crash, so it's probably some leak.

There is still a problem with the glyph/zFont changes. The text of the console (F10) is no longer correctly aligned. I haven't digged into that yet.

**Comment by kapitaenzufall** [comment]
Do you mean the empty line at the bottom of the console window? This is caused because I have manually adjust the height of the topic categories at zFont.cpp line 170-171. I am sorry, I thought this would affect only multiline text ( text which contains a '\n' character ). At the moment I am not sure why this is happening. I ll have a further look.

**Comment by kapitaenzufall** [comment]
Ok I got it, the console text is a multiline text...

**Comment by markusobi** [comment]
REGoth uses the original glyphs as far as I know. Some time ago I added 1 Pixel horizontal space between glyphs, because the original does it too.

Dialogsystem & Console uses some hacky multi line text drawing. Could be done prettier maybe.

There is still some issue with the Zenlib submodule commit. Travis doesn't build and on my PC the specified Zenlib commit doesn't exist. Is it some unpublished Zenlib commit?
If you just want to have the latest Zenlib commit, you can do the following:
`cd lib/Zenlib`
`git checkout master #checks out master branch of Zenlib`
`cd ../../`
`git add lib/Zenlib`
and commit & push.

**Comment by kapitaenzufall** [comment]
After three commits I have finally managed to make Travis happy.

@markusobi The additional horizontal pixel should in my case no problem. I asked because at the moment there are only 20 topic entrys listed rather then 21 like in the original ones. For 21 entrys there is not enough space for a equal margin of the top and bottom entry.

**Pull request merged**
