### PR TITLE
Fix #44 Don't update animation when menu is active

### LINKED ISSUE #44: Character does not stop moving when opening a menu while running
(see title)

### PR DESCRIPTION
**Pull request by rose27**
Ok, I think i fixed the issue.

### CODE REVIEW

**Comment by degenerated1123** [comment]
That disables all animations when a menu is active, which is not what we want. That check would be better placed inside the player controller on the input-function for the player. Not sure what it's called right now, though.

**Comment by rose27** [comment]
Check is in the player controller and active menu resets key states.

**Comment by Kaffeine** [comment]
Do you speak about main menu as well? I think that we should pause the game on main menu showed. Something like at [GameEngine.cpp:54](https://github.com/REGoth-project/REGoth/blob/cb1f2b66a6bafb4c6f0dcd275c9762ded9b7a1a2/src/engine/GameEngine.cpp#L54). Probably we need a setter/getter for m_disableLogic.

**Comment by degenerated1123** [comment]
Does the original actually pause the game on something like the status screen or the log?

**Comment by Kaffeine** [comment]
IIRC time is ticking when you're in N-button menu (menu with current time) and I believe that game is paused during main menu, but I'm not sure about others.

**Comment by degenerated1123** [comment]
We should then rather let the menu itself decide to pause or unpause the game. This fix is only for the player moving forward endlessly when you opened the menu while running, so it's a different story.

**Comment by Kaffeine** [comment]
Oh, you're right.
I was confused but the PR title, but the code looks good to me.

**Pull request merged**
